const deck = [
  {
    img: "./assets/A-Spades.png",
    name: "A",
    suit: "♠️",
    value: 11,
  },
  {
    img: "./assets/A-Diamonds.png",
    name: "A",
    suit: "♦️",
    value: 11,
  },
  {
    img: "./assets/A-Clubs.png",
    name: "A",
    suit: "♣️",
    value: 11,
  },
  {
    img: "./assets/A-Hearts.png",
    name: "A",
    suit: "♥️",
    value: 11,
  },
  {
    img: "./assets/2-Spades.png",
    name: "2",
    suit: "♠",
    value: 2,
  },
  {
    img: "./assets/2-Diamonds.png",
    name: "2",
    suit: "♦️",
    value: 2,
  },
  {
    img: "./assets/2-Clubs.png",
    name: "2",
    suit: "♣",
    value: 2,
  },
  {
    img: "./assets/2-Hearts.png",
    name: "2",
    suit: "♥️",
    value: 2,
  },
  {
    img: "./assets/3-Spades.png",
    name: "3",
    suit: "♠",
    value: 3,
  },
  {
    img: "./assets/3-Diamonds.png",
    name: "3",
    suit: "♦",
    value: 3,
  },
  {
    img: "./assets/3-Clubs.png",
    name: "3",
    suit: "♣",
    value: 3,
  },
  {
    img: "./assets/3-Hearts.png",
    name: "3",
    suit: "♥",
    value: 3,
  },
  {
    img: "./assets/4-Spades.png",
    name: "4",
    suit: "♠",
    value: 4,
  },
  {
    img: "./assets/4-Diamonds.png",
    name: "4",
    suit: "♦",
    value: 4,
  },
  {
    img: "./assets/4-Clubs.png",
    name: "4",
    suit: "♣",
    value: 4,
  },
  {
    img: "./assets/4-Hearts.png",
    name: "4",
    suit: "♥",
    value: 4,
  },
  {
    img: "./assets/5-Spades.png",
    name: "5",
    suit: "♠",
    value: 5,
  },
  {
    img: "./assets/5-Diamonds.png",
    name: "5",
    suit: "♦",
    value: 5,
  },
  {
    img: "./assets/5-Clubs.png",
    name: "5",
    suit: "♣",
    value: 5,
  },
  {
    img: "./assets/5-Hearts.png",
    name: "5",
    suit: "♥",
    value: 5,
  },
  {
    img: "./assets/6-Spades.png",
    name: "6",
    suit: "♠",
    value: 6,
  },
  {
    img: "./assets/6-Diamonds.png",
    name: "6",
    suit: "♦",
    value: 6,
  },
  {
    img: "./assets/6-Clubs.png",
    name: "6",
    suit: "♣",
    value: 6,
  },
  {
    img: "./assets/6-Hearts.png",
    name: "6",
    suit: "♥",
    value: 6,
  },
  {
    img: "./assets/7-Spades.png",
    name: "7",
    suit: "♠",
    value: 7,
  },
  {
    img: "./assets/7-Diamonds.png",
    name: "7",
    suit: "♦",
    value: 7,
  },
  {
    img: "./assets/7-Clubs.png",
    name: "7",
    suit: "♣",
    value: 7,
  },
  {
    img: "./assets/7-Hearts.png",
    name: "7",
    suit: "♥",
    value: 7,
  },
  {
    img: "./assets/8-Spades.png",
    name: "8",
    suit: "♠",
    value: 8,
  },
  {
    img: "./assets/8-Diamonds.png",
    name: "8",
    suit: "♦",
    value: 8,
  },
  {
    img: "./assets/8-Clubs.png",
    name: "8",
    suit: "♣",
    value: 8,
  },
  {
    img: "./assets/8-Hearts.png",
    name: "8",
    suit: "♥",
    value: 8,
  },
  {
    img: "./assets/9-Spades.png",
    name: "9",
    suit: "♠",
    value: 9,
  },
  {
    img: "./assets/9-Diamonds.png",
    name: "9",
    suit: "♦",
    value: 9,
  },
  {
    img: "./assets/9-Clubs.png",
    name: "9",
    suit: "♣",
    value: 9,
  },
  {
    img: "./assets/9-Hearts.png",
    name: "9",
    suit: "♥",
    value: 9,
  },
  {
    img: "./assets/10-Spades.png",
    name: "10",
    suit: "♠",
    value: 10,
  },
  {
    img: "./assets/10-Diamonds.png",
    name: "10",
    suit: "♦",
    value: 10,
  },
  {
    img: "./assets/10-Clubs.png",
    name: "10",
    suit: "♣",
    value: 10,
  },
  {
    img: "./assets/10-Hearts.png",
    name: "10",
    suit: "♥",
    value: 10,
  },
  {
    img: "./assets/J-Spades.png",
    name: "J",
    suit: "♠",
    value: 10,
  },
  {
    img: "./assets/J-Diamonds.png",
    name: "J",
    suit: "♦",
    value: 10,
  },
  {
    img: "./assets/J-Clubs.png",
    name: "J",
    suit: "♣",
    value: 10,
  },
  {
    img: "./assets/J-Hearts.png",
    name: "J",
    suit: "♥",
    value: 10,
  },
  {
    img: "./assets/Q-Spades.png",
    name: "Q",
    suit: "♠",
    value: 10,
  },
  {
    img: "./assets/Q-Diamond.png",
    name: "Q",
    suit: "♦",
    value: 10,
  },
  {
    img: "./assets/Q-Clubs.png",
    name: "Q",
    suit: "♣",
    value: 10,
  },
  {
    img: "./assets/Q-Hearts.png",
    name: "Q",
    suit: "♥",
    value: 10,
  },
  {
    img: "./assets/K-Spades.png",
    name: "K",
    suit: "♠",
    value: 10,
  },
  {
    img: "./assets/K-Diamonds.png",
    name: "K",
    suit: "♦",
    value: 10,
  },
  {
    img: "./assets/K-Clubs.png",
    name: "K",
    suit: "♣",
    value: 10,
  },
  {
    img: "./assets/K-Hearts.png",
    name: "K",
    suit: "♥",
    value: 10,
  },
];

export default deck;
